# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name=b'start date')),
                ('end_date', models.DateTimeField(verbose_name=b'end date')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name=b'start date')),
                ('end_date', models.DateTimeField(verbose_name=b'end date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Employee')),
            ],
        ),
    ]
