# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateslot',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='slot.Candidate'),
        ),
        migrations.AlterField(
            model_name='employeeslot',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='slot.Employee'),
        ),
    ]
